{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-svacer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
stringData:
  PG_PASS: "{{ .Values.database.password }}"
  PG_USER: "{{ .Values.database.username }}"
  PG_DB: "{{ .Values.database.database }}"
  PG_HOST: "{{ .Values.database.host }}"
  PG_PORT: "{{ .Values.database.port }}"
{{- end }}

