---
apiVersion: v2
name: svacer
appVersion: 9.0.2
version: 0.3.0
description: 
home: https://svacer.ispras.ru/mediawiki
icon: https://svacer.ispras.ru/mediawiki/images/6/6b/Knight_icon.png
keywords:
  - svacer
source:
  - https://github.com/rickraven/helm-svacer
maintainers:
  - name: rickraven
    email: kapitonov.stas200@gmail.com
    url: https://github.com/rickraven

