---
apiVersion: v2
name: svacer
appVersion: 10.0.1
version: 0.5.0
description: Svacer - server for storing and processing static analysis results. Supports import of analysis results from Svace directly and from other analyzers via the format SARIF
home: https://svacer.ispras.ru/mediawiki
icon: https://svacer.ispras.ru/mediawiki/images/6/6b/Knight_icon.png
keywords:
  - svacer
  - sarif
  - security
  - analysis
source:
  - https://github.com/rickraven/helm-svacer
maintainers:
  - name: rickraven
    email: kapitonov.stas200@gmail.com
    url: https://github.com/rickraven

